plugins:
  shop_enabled:
    default: true
    client: true
  shop_currency:
    default: "CNY"
    client: true
  shop_supported_gateways:
    default: "wechat,paypal"
    client: true
  shop_allow_guest_checkout:
    default: false
    client: true
